name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important for git history
      
      - name: Build and deploy with Docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          docker build -t deployer .
          docker run \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e GH_DEPLOY_TOKEN \
            -e GITHUB_REPOSITORY \
            deployer