name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Build and deploy with Docker
        env:
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          docker build -t deployer .
          docker run \
            --env-file <(env | grep AWS) \
            -e GH_DEPLOY_TOKEN \
            -e GITHUB_REPOSITORY \
            deployer